[package]
name = "dynamodel_tests"
version = "0.3.1"
authors = ["Kanji Tanaka <sumireminami@gmail.com"]
edition = "2021"
publish = false

[dependencies]
dynamodel = { path = "../dynamodel" }
aws-sdk-dynamodb = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
trybuild = "1"
